# Generated by Django 5.0.1 on 2024-06-04 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mobil', '0001_initial'),
        ('pesanan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='id_mobils',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobil.mobils'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='id_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesanan.order'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='id_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesanan.order'),
        ),
    ]
