# Generated by Django 5.0.1 on 2024-06-04 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mobil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentTestimonial', models.CharField(max_length=200)),
                ('rating', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('id_mobil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobil.mobils')),
            ],
        ),
    ]
