# Generated by Django 5.0.1 on 2024-06-05 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesanan', '0002_initial'),
        ('testi', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonialrating',
            name='id_return_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pesanan.returnorder'),
        ),
    ]
